transcendence/User/urls.py
# User/urls.py
from django.urls import path
from . import views

app_name = 'User'

urlpatterns = [
    path('login/', views.login_view, name='login'),  # Vue pour rendre le formulaire de connexion
    path('submit_login/', views.submit_login, name='submit_login'),  # Vue pour traiter la soumission AJAX
    path('profile/<str:username>/', views.profile_view, name='profile'),
    path('submit_registration/', views.submit_registration, name='submit_registration'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),

    ###### Gestion de profil ######
    path('gestion-profil/', views.manage_profile_view, name='gestion_profil'),
    path('change_password/', views.change_password_view, name='change_password'),
    path('update-avatar/', views.update_avatar_view, name='update_avatar'),
    path('update-profile/', views.update_profile_view, name='update_profile'),
	path('enable-2fa/', views.enable_2fa, name='enable_2fa'),
    path('disable-2fa/', views.disable_2fa, name='disable_2fa'),
	path('qr-code/', views.enable_2fa, name='show_qr'),
	path('verify-2fa/', views.verify_2fa, name='verify_2fa'),
    
    path('match-history/', views.match_history_view, name='match_history'),
    path('send-friend-request/<int:to_user_id>/', views.send_friend_request, name='send_friend_request'),
    path('accept-friend-request/<int:request_id>/', views.accept_friend_request, name='accept_friend_request'),
    path('reject-friend-request/<int:request_id>/', views.reject_friend_request, name='reject_friend_request'),
    path('update-avatar/', views.update_avatar_view, name='update_avatar'),
    path('log-guest/', views.log_guest_view, name='log_guest'),
	path('verify-2fa-login/', views.verify_2fa_login, name='verify_2fa_login'),

]

transcendence/accounts/urls.py
# ---- Imports standard ----
import logging

# ---- Imports tiers ----
from django.urls import path

# ---- Imports locaux ----
from .views.register import RegisterView
from .views.manageProfile import (
    ManageProfileView, UpdateProfileView, DeleteAccountView,
    ChangePasswordView, UpdateAvatarView
)
from .views.profile import ProfileView
from .views.logout import LogoutView
from .views.burgerMenu import BurgerMenuView, UpdateStatusView
from .views.friendProfile import FriendProfileView
from .views.login import LoginView
from .views.manageFriends import AddFriendView, HandleFriendRequestView, RemoveFriendView
from .views.login2fa import Enable2FAView, Check2FAView, Login2faView, Disable2FAView
from .views.tokenManagement import RefreshJwtView
from .views.setLanguage import SetLanguageView
from django.views.i18n import set_language

# ---- Configuration ----
logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.DEBUG)
logger.debug("Rentre dans urls.py de app accounts")

# ---- Application namespace ----
app_name = 'accounts'

# ---- URL patterns ----
urlpatterns = [
    # ---- Manage Profile ----
    path('gestion_profil/', ManageProfileView.as_view(), name='manage_profile'),
    path('profile/update/', UpdateProfileView.as_view(), name='update_profile'),
    path('profile/delete_account/', DeleteAccountView.as_view(), name='delete_account'),
    path('profile/change_password/', ChangePasswordView.as_view(), name='change_password'),
    path('profile/update_avatar/', UpdateAvatarView.as_view(), name='update_avatar'),

    # ---- Manage 2FA ----
    path('2fa/enable/', Enable2FAView.as_view(), name='enable_2fa'),
    path('2fa/check/', Check2FAView.as_view(), name='check_2fa'),
    path('2fa/login2fa/', Login2faView.as_view(), name='login_2fa'),
    path('2fa/disable/', Disable2FAView.as_view(), name='disable_2fa'),

    # ---- Manage Friends ----
    path('friends/add/', AddFriendView.as_view(), name='add_friend'),
    path('friends/handle-request/', HandleFriendRequestView.as_view(), name='handle_friend_request'),
    path('friends/remove/', RemoveFriendView.as_view(), name='remove_friend'),

    # ---- Burger Menu ----
    path('burgerMenu/', BurgerMenuView.as_view(), name='burgerMenu'),
    path('burgerMenu/update-status/', UpdateStatusView.as_view(), name='update_status'),

    # ---- Friend Profile ----
    path('friend/<str:friend_username>/', FriendProfileView.as_view(), name='friend_profile'),

    # ---- Login ----
    path('login/', LoginView.as_view(), name='login'),
    path('submit_login/', LoginView.as_view(), name='submit_login'),

    # ---- Logout ----
    path('logout/', LogoutView.as_view(), name='logout'),

    # ---- Register ----
    path('register/', RegisterView.as_view(), name='register'),
    path('submit_register/', RegisterView.as_view(), name='submit_register'),

    # ---- User Profile ----
    path('userProfile/', ProfileView.as_view(), name='user_profile'),

    # ---- Token Management ---- #
    path('refreshJwt/', RefreshJwtView.as_view(), name='refresh_jwt'),

	# ---- Internationalization ----
	#path('set_language/', set_language, name='set_language'),
    path('set_language/', SetLanguageView.as_view(), name='set_language'),


    # ---- Token Authentication (commented for now) ----
    # path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    # path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

transcendence/transcendence/urls.py
# urls.py

from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.conf.urls.i18n import i18n_patterns

import logging

from core.views import landing_view  # Import direct de la view

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.DEBUG)

logger.debug("Entrée dans urls.py de l'app Transcendence")

urlpatterns = [
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('game/', include('game.urls', namespace='game')),
    path('core/', include('core.urls', namespace='core')),
    # Supprimez ou commentez cette ligne si elle interfère avec la route de fallback
    # path('', include(('core.urls', 'core'), namespace='landing')),
]

if settings.DEBUG:
    # Servir les fichiers statiques en développement
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # Servir les fichiers média en développement
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Route de fallback pour servir landing.html pour toutes les autres URLs
urlpatterns += [
    re_path(r'^.*$', TemplateView.as_view(template_name='landing.html')),
    path('i18n/', include('django.conf.urls.i18n')),
]

transcendence/User/models.py
# User/models.py
from django.db import models
from django.utils import timezone
from pathlib import Path
from django.contrib.auth.models import User
import random
from datetime import datetime, timedelta


class User(models.Model):
    username = models.CharField(max_length=150, unique=True)
    email = models.EmailField(unique=True)
    password_hash = models.CharField(max_length=256)  # Hachage du mot de passe
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_2fa_enabled = models.BooleanField(default=False)
    totp_secret = models.CharField(max_length=32, null=True, blank=True)
    avatar = models.ImageField(
        upload_to='avatars/',
        null=True,
        blank=True,
        default='avatars/default_avatar.png'  # Chemin vers l'image par défaut
    )
    
    def __str__(self):
        return self.username

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    bio = models.TextField(max_length=500, blank=True)
    is_online = models.BooleanField(default=False)
    
    def __str__(self):
        return f"Profile de {self.user.username}"

class FriendRequest(models.Model):
    from_user = models.ForeignKey(User, related_name='friend_requests_sent', on_delete=models.CASCADE)
    to_user = models.ForeignKey(User, related_name='friend_requests_received', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        max_length=10,
        choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')],
        default='pending'
    )
    
    def __str__(self):
        return f"{self.from_user} to {self.to_user} - {self.status}"

class Game(models.Model):
    player1 = models.ForeignKey(User, related_name='games_as_player1', on_delete=models.CASCADE)
    player2 = models.ForeignKey(User, related_name='games_as_player2', on_delete=models.CASCADE)
    score_player1 = models.IntegerField(default=0)
    score_player2 = models.IntegerField(default=0)
    timestamp = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=[('ongoing', 'Ongoing'), ('finished', 'Finished')], default='ongoing')
    
    def __str__(self):
        return f"Game {self.id} - {self.player1} vs {self.player2}"

class MatchHistory(models.Model):
    user = models.ForeignKey(User, related_name='match_histories', on_delete=models.CASCADE)
    game = models.ForeignKey(Game, related_name='match_histories', on_delete=models.CASCADE)
    result = models.CharField(max_length=10, choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw')])
    played_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.user} - {self.game} - {self.result}"


class TwoFactorCode(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    code = models.CharField(max_length=6)
    created_at = models.DateTimeField(auto_now_add=True)
    
    @classmethod
    def generate_code(cls, user):
        # Delete old codes
        cls.objects.filter(user=user).delete()
        # Generate new code
        code = ''.join([str(random.randint(0, 9)) for _ in range(6)])
        return cls.objects.create(user=user, code=code)
    
    def is_valid(self):
        # Code expires after 10 minutes
        return datetime.now() - timedelta(minutes=10) <= self.created_at.replace(tzinfo=None)

transcendence/accounts/models.py
# User/models.py
# ---- Imports standard ----
import random
from datetime import datetime, timedelta
from pathlib import Path

# ---- Imports tiers ----
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.utils.timezone import now


#[DOCUMENTATION] <Django - User & Abstract User>

class CustomUser(AbstractUser):
    """Utilisateur personnalisé."""
    is_2fa_enabled = models.BooleanField(default=False)
    totp_secret = models.CharField(max_length=32, null=True, blank=True)
    friends = models.ManyToManyField('self', symmetrical=True, blank=True)
    avatar = models.ImageField(
        upload_to='avatars/',
        null=True,
        blank=True,
        default='avatars/default_avatar.png'
    )
    is_online = models.BooleanField(default=False)

    def match_history(self):
        """Retourne l'historique des parties jouées par l'utilisateur."""
        return GameResult.objects.filter(
            models.Q(player1=self) | models.Q(player2=self)
        ).order_by('-date')

    def __str__(self):
        return self.username




class FriendRequest(models.Model):
    from_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='friend_requests_sent',
        on_delete=models.CASCADE
    )
    to_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='friend_requests_received',
        on_delete=models.CASCADE
    )
    timestamp = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        max_length=10,
        choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')],
        default='pending'
    )

    def __str__(self):
        return f"{self.from_user} to {self.to_user} - {self.status}"


class TwoFactorCode(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    code = models.CharField(max_length=6)
    created_at = models.DateTimeField(auto_now_add=True)

    @classmethod
    def generate_code(cls, user):
        # Supprimer les anciens codes
        cls.objects.filter(user=user).delete()
        # Générer un nouveau code
        code = ''.join([str(random.randint(0, 9)) for _ in range(6)])
        return cls.objects.create(user=user, code=code)

    def is_valid(self):
        # Le code expire après 10 minutes
        return datetime.now() - timedelta(minutes=10) <= self.created_at.replace(tzinfo=None)


# Stocker les refresh tokens en base de donnee 
# pour pouvoir les comparer a ceux que l' utilisateur nous envoie
# la validite des access tokens est elle geree par PyJWT
class RefreshToken(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='refresh_tokens')
    token = models.CharField(max_length=255, unique=True)  # Le token JWT
    created_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField()
    is_blacklisted = models.BooleanField(default=False)  # Permet de marquer un token comme blacklisté (déconnecté) avoir si utile


    def is_expired(self):
        """Vérifie si le token a expiré"""
        return now() > self.expires_at
    
    def is_valid(self):
        return not self.is_expired() and not self.is_blacklisted

    def __str__(self):
        return f"RefreshToken(user={self.user}, expires_at={self.expires_at})"

transcendence/accounts/views/burgerMenu.py
# ---- Imports standard ----
import logging

# ---- Imports tiers ----
from django.http import JsonResponse
from django.views import View
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.shortcuts import render
from django.template.loader import render_to_string


# ---- Imports locaux ----
from accounts.models import FriendRequest
from game.models import GameInvitation

# ---- Configuration ----
logger = logging.getLogger(__name__)
User = get_user_model()

def get_burger_menu_context(user):
    """
    Retourne le contexte nécessaire pour le template du burger menu.
    """
    default_avatar = '/media/avatars/default_avatar.png'
    return {
        'user': user,
        'friends': user.friends.all(),
        'friend_requests': FriendRequest.objects.filter(to_user=user),
        'game_invitations': GameInvitation.objects.filter(to_user=user, status='pending'),
        'avatar_url': user.avatar.url if user.avatar else default_avatar,
    }

class BurgerMenuView(View):
    """
    Handle retrieval of user data for the burger menu.
    """

    @method_decorator(login_required)
    def get(self, request):
        """
        Render the burger menu with user data, friends list, and friend requests.
        """
        try:
            context = get_burger_menu_context(request.user)
            burger_menu_html = render_to_string('accounts/burger_menu.html', context)
            return JsonResponse({'status': 'success', 'html': burger_menu_html})
        except Exception as e:
            logger.error(f"Erreur lors de la récupération des données du menu burger: {e}")
            return JsonResponse({'status': 'error', 'message': str(e)}, status=500)


@method_decorator([csrf_protect, login_required], name='dispatch')
class UpdateStatusView(View):
    """
    Handle updating the user's online/offline status.
    """

    def post(self, request):
        """
        Update the user's online/offline status.
        """
        user = request.user
        status = request.POST.get('status')

        logger.info(f"--Requête de mise à jour du statut pour {user.username}: {status}")

        if status not in ['online', 'offline']:
            return JsonResponse({'status': 'error', 'message': 'Statut non valide'}, status=400)

        # Update the user's status
        user.is_online = (status == 'online')
        user.save()

        logger.info(f"Statut mis à jour pour {user.username}: {user.is_online}")
        return JsonResponse({'status': 'success', 'message': 'Statut mis à jour avec succès', 'is_online': user.is_online})

transcendence/templates/accounts/disable_2fa.html
{% load i18n %}
<div class="container-fluid d-flex justify-content-center mt-3" style="height: 100%; padding-top: 20px; z-index: 10;">
	<div class="col-12 col-sm-10 col-md-8 col-lg-5 col-xl-4 col-xxl-4">

		<h2 class="text-white texte-center mb-3" style="font-size: 2em;">{% trans "Désactiver l'authentification à deux facteurs" %}</h2>

		<div class=" dfa-item d-flex flex-column align-items-center justify-content-between text-white p-4">
			<p>{% trans "Entrez le code généré par votre application d'authentification." %}</p>
			<form id="disable-2fa-form" method="POST">
				{% csrf_token %}
				<div class="d-flex flex-column form-group w-100">
					<label for="id_code">{% trans "Code 2FA :" %}</label>
					{{ disable_form.code }}
				</div> 
				<button type="submit" class="btn btn-danger btn-70">{% trans "Désactiver 2FA" %}</button>
			</form>
		</div>

	</div>
</div>
<style>
	.dfa-item {
		background-color:  #101A32;
		border: 2px solid rgb(153, 148, 148);
		border-radius: 20px;
		font-style: "Jersey 10";
		color: white;
		font-size: 1.2em;
		min-width: 300px;
	}
</style>

transcendence/templates/accounts/enable_2fa.html
{% load i18n %}
<div class="container-fluid d-flex justify-content-center mt-3" style="height: 100%; padding-top: 20px; z-index: 10;">
	<div class="col-12 col-sm-10 col-md-8 col-lg-5 col-xl-4 col-xxl-4">
		<h2 class="text-white texte-center mb-3" style="font-size: 2em;">{% trans "Activer l'authentification à deux facteurs" %}</h2>


			<div class=" dfa-item d-flex flex-column align-items-center justify-content-between text-white p-4">
							<div class="form-group mb-0">
								<div class="qr-container p-2 mt-2" style="background: white; padding: 20px; display: inline-block; border-radius: 10px;">
									{% if qr_code %}
										<img src="data:image/png;base64,{{ qr_code }}" 
												alt="QR Code" 
												style="display: block; max-width: 200px; height: auto;">
									{% else %}
										<div style="color: red;">{% trans "QR Code non disponible" %}</div>
									{% endif %}
								</div>
								
								<!-- <p style="color: white; font-family: 'Jersey 10'; margin: 20px 0;">
									{% trans "Code secret" %}: <strong>{{ secret|default:"N/A" }}</strong>
								</p> -->
								
								<form id="verify-2fa-form" method="POST">
									{% csrf_token %}
									<div class="d-flex flex-column form-group w-100;">
										<label for="id_code">{% trans "Code 2FA :" %}</label>
										{{ 2FA_form.code }}
									</div> 
									<button type="submit" 
											class="btn btn-primary btn-70"
											style="background-color: #2DB4F3;
													border: none;
													font-family: 'Jersey 10';
													font-size: 18px;">
										{% trans "Vérifier" %}
									</button>
									<div class="verification-error text-danger mt-2" style="display: none;"></div>
									<div class="verification-success text-success mt-2" style="display: none;"></div>
								</form>
							</div>
			</div>
	</div>




</div>

<style>

	.html, body{
		overflow: auto;
	}

	.dfa-item {
		background-color:  #101A32;
		border: 2px solid rgb(153, 148, 148);
		border-radius: 20px;
		min-width: 300px;
	}
</style>

transcendence/templates/accounts/friend_profile.html
{% load static %}
{% load i18n %}
<div class="container-fluid mt-4" style="height: 100%; ">
	<h1 class="text-center title mb-4" style="min-width: 300px;">{% trans "Profil de" %} {{ friend.username }}</h1>

    <!-- Informations du profil -->
    <div class="row d-flex justify-content-center mb-4">
        <div class="col-12 col-sm-8 col-md-6 col-lg-5 col-xl-4 col-xxl-4">
            <div class="card p-4">
                <div class="profile-info d-flex flex-column justify-content-center align-items-center">
                    <img src="{{ avatar_url }}" alt="Avatar" style="width: 120px; height: 120px; border-radius: 50%;" class="mb-3">
                    <div class="mt-3">
                        <h3>{% trans "Pseudo : " %}{{ friend.username }}</h3>
                        <p class="mb-0">{% trans "Nombre de matchs joués : " %}<strong>{{ match_count|default:"N/A" }}</strong></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Section Statistiques -->
	<div class="row d-flex justify-content-center mb-4">
		<div class="col-12 col-sm-8 col-md-6 col-lg-5 col-xl-4 col-xxl-4">
			<div class="statistics text-center">
				<h4 class="stat-title">{% trans "Statistiques Générales" %}</h4>
				<ul class="list-group list-group-flush">
					<li class="list-group-item bg-transparent text-white">{% trans "Victoires : " %}{{ victories }}</li>
					<li class="list-group-item bg-transparent text-white">{% trans "Défaites : " %}{{ defeats }}</li>
					<li class="list-group-item bg-transparent text-white">{% trans "Meilleur score : " %}{{ best_score }} pts</li>
				</ul>
			</div>
		</div>
	</div>

	<!-- Section Historique des matchs -->
    <div class="row d-flex justify-content-center mb-4">
        <div class="col-12 col-sm-8 col-md-6 col-lg-5 col-xl-4 col-xxl-4">
            <div class="match-history text-center">
                <h4 class="stat-title">{% trans "Historique des Matchs" %}</h4>
                {% if match_histories %}
                    <ul class="list-group list-group-flush">
                        {% for match in match_histories %}
                            <li class="list-group-item bg-transparent text-white">
                                <strong>{% trans "Adversaire : " %}</strong>{{ match.opponent.username }}<br>
                                <strong>{% trans "Résultat : " %}</strong>{% if match.result == "win" %}{% trans "Victoire" %}{% else %}{% trans "Défaite" %}{% endif %}<br>
                                <strong>{% trans "Joué le : " %}</strong>{{ match.played_at|date:"d/m/Y H:i" }}
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>{% trans "Aucun match enregistré pour le moment." %}</p>
                {% endif %}
            </div>
        </div>
    </div>

     <!-- Section Amis -->
	<div class="row d-flex justify-content-center mb-0">
		<div class="col-12 col-sm-8 col-md-6 col-lg-5 col-xl-4 col-xxl-4">
			<div class="friends-section text-center">
				<h4 class="stat-title">{% trans "Amis" %}</h4>
				<p>{% trans "Nombre d'amis : " %}<strong>{{ friends_count }}</strong></p>
			</div>
		</div>
	</div>
</div>

<!-- Styles spécifiques -->
<style>
	.html, body {
		overflow: auto;
	}
	.card {
		background-color:  #101A32;
		border: 2px solid rgb(153, 148, 148);
		min-width: 300px;
		color: white;
	}
	body {
		background-color: #101A32;
		color: white;
	}
		h1, .card-title, .stat-title {
		color: #2DB4F3;
	}
	.profile-info {
		display: flex;
		align-items: center;
	}
	.profile-info img {
		width: 120px;
		height: 120px;
		border-radius: 50%;
		margin-right: 20px;
	}
	
	.statistics, .friends-section, .match-history {
        background-color: #101A32;
        border: 2px solid rgb(153, 148, 148);
        padding: 20px;
        border-radius: 10px;
        min-width: 300px;
    }


</style>

transcendence/templates/accounts/login.html
{% load i18n %}
<!-- Conteneur pour les boutons -->
<div id="login" class=" container-fluid d-flex flex-column align-items-center text-center" style="height: 100%; padding-top: 70px;">
	<div class="col-8 col-sm-6 col-md-6 col-lg-4 col-xl-3 col-xxl-3">
		<h1 class="text-center text-white title mb-3">{% trans "Connexion" %}</h1>
        <form id="login-form" method="POST">
			{% csrf_token %}
            <div class="form-group mb-2">

				<label for="username" class="form-label text-white w-100">{% trans "Nom d'utilisateur :" %}</label>
				<input type="text" class="form-control w-100" id="username" name="username" required>
			</div>
			<div class="form-group mb-2">
				<label for="password" class="form-label text-white w-100">{% trans "Mot de passe :" %}</label>
				<input type="password" class="form-control w-100" id="password" name="password" required>
			</div>
			<div class="forgot-password text-center mb-2">
				<a href="#" class="text-info">{% trans "Mot de passe oublié ?" %}</a> <!--A Faire-->
			</div>
				<button id= "validate-btn" type="submit" class=" btn btn-primary btn-70 mb-4">{% trans "Valider" %}</button>
                <div id="login-error" class="text-danger mt-2"></div>
		</form>
	</div>
</div>
<script>
	
</script>

<style>
	html, body {
		overflow-y: auto;
	}
	
	.btn-primary {
		min-width: 100px;
	}

</style>

transcendence/templates/accounts/login2fa.html
{% load i18n %}
<div class="container-fluid d-flex justify-content-center mt-3" style="height: 100%; padding-top: 20px; z-index: 10;">
	<div class="col-12 col-sm-10 col-md-8 col-lg-5 col-xl-4 col-xxl-4">
		
		<div class=" dfa-item d-flex flex-column align-items-center justify-content-between text-white p-4">
			<div class="login_2fa_div d-flex flex-column form-group mb-0">
			<h3>{% trans "Entrez Code 2FA" %}</h3>

				<p>{% trans "Pour vous connecter, veuillez saisir le code 2FA depuis votre application d'authentification" %}.</p>
				<form id="login-2fa-form" method="POST" >
					{% csrf_token %}
					<div class="d-flex flex-column form-group">
							<label for="code">{% trans "Code 2FA :" %}</label>
							{{ login2fa_form.code}}
					</div>
					<button type="submit" class="btn btn-primary btn-70">{% trans "Valider" %}</button>
				</form>
			</div>

		</div>
	</div>
</div>
<style>
	.dfa-item {
		background-color:  #101A32;
		border: 2px solid rgb(153, 148, 148);
		border-radius: 20px;
		font-style: "Jersey 10";
		color: white;
		font-size: 1.2em;
		min-width: 320px;
	}
</style>

transcendence/templates/accounts/match_history.html
<!-- templates/User/match_history.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Historique des Parties</title>
</head>
<body>
    <h1>Historique des Parties</h1>
    <table>
        <thead>
            <tr>
                <th>Partie</th>
                <th>Résultat</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            {% for history in match_histories %}
            <tr>
                <td>{{ history.game }}</td>
                <td>{{ history.get_result_display }}</td>
                <td>{{ history.played_at }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

transcendence/templates/accounts/verify_2fa_login.html
{% load i18n %}
<div class="container-fluid d-flex justify-content-center mt-3" style="height: 100%; padding-top: 20px; z-index: 10;">
	<div class="col-12 col-sm-10 col-md-8 col-lg-5 col-xl-4 col-xxl-4">
		
		<div class=" dfa-item d-flex flex-column align-items-center justify-content-between text-white p-4">
			<div class="login_2fa_div d-flex flex-column form-group mb-0">
			<h3>{% trans "Entrez Code 2FA" %}</h3>

				<p>{% trans "Pour vous connecter, veuillez saisir le code 2FA depuis votre application d'authentification" %}.</p>
				<form id="login-2fa-form" method="POST" >
					{% csrf_token %}
					<div class="d-flex flex-column form-group">
							<label for="id_code">{% trans "Code 2FA :" %}</label>
							{{ login_2fa_form.code }}
					</div>
					<button type="submit" class="btn btn-primary btn-70">{% trans "Valider" %}</button>
				</form>
			</div>

		</div>
	</div>
</div>
<style>
	.dfa-item {
		background-color:  #101A32;
		border: 2px solid rgb(153, 148, 148);
		border-radius: 20px;
		font-style: "Jersey 10";
		color: white;
		font-size: 1.2em;
		min-width: 320px;
	}
</style>